services:
  gitleaks:
    image: zricethezav/gitleaks:v8.30.1
    volumes:
      - ./:/workspace
    working_dir: /workspace
    profiles: ["scan"]

  trufflehog:
    image: trufflesecurity/trufflehog:3.97.0
    volumes:
      - ./:/workspace
    working_dir: /workspace
    profiles: ["scan"]
