apiVersion: v1
kind: Namespace
metadata:
  name: k8s-lab
  labels:
    app.kubernetes.io/part-of: k8s-lab
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
