apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: k8s-lab
type: Opaque
stringData:
  DB_HOST: "postgres.k8s-lab.svc.cluster.local"
  DB_PORT: "5432"
  DB_USER: "app_user"
  DB_PASSWORD: "change-me-in-production"
  DB_NAME: "k8s_lab"
