#!/usr/bin/env bash
# Provisions the real-Azure equivalents of this lab's mock setup:
#   - api-b app registration (with a scope + app-role)
#   - api-a app registration (with delegated + app perms on api-b)
#   - daemon-app app registration (with app perms on api-b)
#   - user-assigned managed identity granted Files.Read.All on api-b
#
# Requires: az CLI, logged in with permission to create app registrations.
# Outputs an .env.azure file you can source to run api-a / api-b against real Entra.

set -euo pipefail

RG="${RG:-rg-azure-auth-lab}"
LOCATION="${LOCATION:-westeurope}"
PREFIX="${PREFIX:-azauthlab$RANDOM}"

echo "Using resource group: $RG  prefix: $PREFIX  location: $LOCATION"

az group create -n "$RG" -l "$LOCATION" -o none

echo ">> Creating api-b app registration"
API_B_APP=$(az ad app create --display-name "$PREFIX-api-b" --query appId -o tsv)
API_B_SP=$(az ad sp create --id "$API_B_APP" --query id -o tsv)
az ad app update --id "$API_B_APP" --identifier-uris "api://$API_B_APP" -o none

# Expose Files.Read scope + Files.Read.All app-role
SCOPE_ID=$(uuidgen)
ROLE_ID=$(uuidgen)
cat > /tmp/api-b-manifest.json <<EOF
{
  "api": {
    "oauth2PermissionScopes": [{
      "id": "$SCOPE_ID", "adminConsentDescription": "Read files on behalf of user",
      "adminConsentDisplayName": "Files.Read", "isEnabled": true, "type": "User",
      "userConsentDescription": "Read your files", "userConsentDisplayName": "Files.Read",
      "value": "Files.Read"
    }]
  },
  "appRoles": [{
    "id": "$ROLE_ID", "allowedMemberTypes": ["Application"], "description": "Read all files",
    "displayName": "Files.Read.All", "isEnabled": true, "value": "Files.Read.All"
  }]
}
EOF
az rest --method PATCH --uri "https://graph.microsoft.com/v1.0/applications(appId='$API_B_APP')" \
  --headers "Content-Type=application/json" --body @/tmp/api-b-manifest.json

echo ">> Creating api-a app registration"
API_A_APP=$(az ad app create --display-name "$PREFIX-api-a" --query appId -o tsv)
API_A_SP=$(az ad sp create --id "$API_A_APP" --query id -o tsv)
az ad app update --id "$API_A_APP" --identifier-uris "api://$API_A_APP" -o none
API_A_SECRET=$(az ad app credential reset --id "$API_A_APP" --query password -o tsv)

echo ">> Granting api-a delegated Files.Read on api-b"
az ad app permission add --id "$API_A_APP" --api "$API_B_APP" --api-permissions "$SCOPE_ID=Scope" -o none
az ad app permission admin-consent --id "$API_A_APP" -o none

echo ">> Creating daemon app registration"
DAEMON_APP=$(az ad app create --display-name "$PREFIX-daemon" --query appId -o tsv)
DAEMON_SP=$(az ad sp create --id "$DAEMON_APP" --query id -o tsv)
DAEMON_SECRET=$(az ad app credential reset --id "$DAEMON_APP" --query password -o tsv)

echo ">> Granting daemon app-role Files.Read.All on api-b"
az rest --method POST \
  --uri "https://graph.microsoft.com/v1.0/servicePrincipals/$DAEMON_SP/appRoleAssignments" \
  --headers "Content-Type=application/json" \
  --body "{\"principalId\":\"$DAEMON_SP\",\"resourceId\":\"$API_B_SP\",\"appRoleId\":\"$ROLE_ID\"}" -o none

echo ">> Creating user-assigned managed identity"
UAMI_NAME="$PREFIX-uami"
az identity create -g "$RG" -n "$UAMI_NAME" -o none
UAMI_PRINCIPAL=$(az identity show -g "$RG" -n "$UAMI_NAME" --query principalId -o tsv)

echo ">> Granting UAMI Files.Read.All on api-b"
az rest --method POST \
  --uri "https://graph.microsoft.com/v1.0/servicePrincipals/$UAMI_PRINCIPAL/appRoleAssignments" \
  --headers "Content-Type=application/json" \
  --body "{\"principalId\":\"$UAMI_PRINCIPAL\",\"resourceId\":\"$API_B_SP\",\"appRoleId\":\"$ROLE_ID\"}" -o none

TENANT=$(az account show --query tenantId -o tsv)

cat > .env.azure <<EOF
# Generated by azure-setup.sh - source this to target real Entra
TENANT_ID=$TENANT
AUTHORITY=https://login.microsoftonline.com/$TENANT
ISSUER=https://login.microsoftonline.com/$TENANT/v2.0
JWKS_URI=https://login.microsoftonline.com/$TENANT/discovery/v2.0/keys

API_A_CLIENT_ID=$API_A_APP
API_A_CLIENT_SECRET=$API_A_SECRET
API_A_AUDIENCE=api://$API_A_APP

API_B_CLIENT_ID=$API_B_APP
API_B_AUDIENCE=api://$API_B_APP

DAEMON_CLIENT_ID=$DAEMON_APP
DAEMON_CLIENT_SECRET=$DAEMON_SECRET

UAMI_NAME=$UAMI_NAME
UAMI_PRINCIPAL_ID=$UAMI_PRINCIPAL
EOF

echo ""
echo "Done. Wrote .env.azure. Resources in $RG. Run ./scripts/azure-cleanup.sh to remove them."
